### ISSUE TITLE
How to Calculate the FLOPs of DeiT-ATS

### ISSUE THREAD

**Issue by ChuanyangZheng** [adaptivetokensampling/ATS#1]
Your adaptive token sampling attracts me a lot.
I am curious how you calculate the FLOPs of DeiT-ATS in Table 1, since the number of selected tokens varies for all images as shown in Figure 6 in paper. Do you calculate the mean of the number of selected tokens for all images?
Thanks~

**Comment by MohsenFayyaz89** [comment]
Thanks for your interest!
Yes, as mentioned in the paper, the reported GFLOPs are averaged over the samples of the validation set of each dataset.

**Comment by HelloWXJ1024** [comment]
Can you share the method that you calculate the FLOPs？I find the FLOPs of DeIT-s-ATS on ImageNet validation is 3.4 instead 2.9 reported in the paper?
